In [2]:
from sklearn.datasets import make_moons


In [3]:
moons = make_moons(n_samples=100, shuffle=True, noise=None, random_state=None)

In [45]:
X = moons[0]
y = moons[1]

In [46]:
y_train

array([1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1])

In [47]:
X_train,X_test,y_train,y_test = X[:80],X[80:],y[:80],y[80:]

In [64]:
X_test.shape[1]

2

In [49]:
len(y_test)

20

In [50]:

#writing chapter 7 code

from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [51]:
log_clf = LogisticRegression()
rnd_clf = RandomForestClassifier()
svm_clf = SVC()

In [52]:
voting_clf = VotingClassifier(
    estimators = [('lr',log_clf),('rf',rnd_clf),('svc',svm_clf)],
    voting = 'hard')
voting_clf.fit(X_train,y_train)

/Users/ushadevi/Desktop/venv/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/ushadevi/Desktop/venv/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Users/ushadevi/Desktop/venv/lib/python3.6/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


VotingClassifier(estimators=[('lr',
                              LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='warn',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=None,
                                                 solver='warn', tol=0.0001,
                                                 verbose=0, warm_start=False)),
                             ('rf',
                              RandomForestClassifier(bootstrap=True,
                                                     class_weight=None,
                                                     criterion='gini',...
                                        

In [53]:
from sklearn.metrics import accuracy_score
for clf in (log_clf,rnd_clf,svm_clf,voting_clf):
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    print(clf.__class__.__name__,accuracy_score(y_test,y_pred))
    

LogisticRegression 0.85
RandomForestClassifier 1.0
SVC 0.95
VotingClassifier 0.95


/Users/ushadevi/Desktop/venv/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/ushadevi/Desktop/venv/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Users/ushadevi/Desktop/venv/lib/python3.6/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Users/ushadevi/Desktop/venv/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWar

In [58]:
# bagging classifier

from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

bag_clf = BaggingClassifier(
    DecisionTreeClassifier(),n_estimators=500,max_samples=20,bootstrap=True,n_jobs=-1
)
bag_clf.fit(X_train,y_train)
y_pred = bag_clf.predict(X_test)
print(bag_clf.__class__.__name__,accuracy_score(y_test,y_pred))

BaggingClassifier 0.9


In [59]:
#out of bag evaluation
bag_clf = BaggingClassifier(
   DecisionTreeClassifier(),n_estimators=500,max_samples=20,bootstrap=True,n_jobs=-1,
    oob_score = True
)
bag_clf.fit(X_train,y_train)
bag_clf.oob_score_

0.9

In [60]:
y_pred = bag_clf.predict(X_test)
accuracy_score(y_test,y_pred)

0.9

In [61]:
bag_clf.oob_decision_function_

array([[0.01546392, 0.98453608],
       [0.1015625 , 0.8984375 ],
       [0.90206186, 0.09793814],
       [0.00779221, 0.99220779],
       [0.97964377, 0.02035623],
       [0.04909561, 0.95090439],
       [0.85148515, 0.14851485],
       [0.20263158, 0.79736842],
       [0.95652174, 0.04347826],
       [0.98987342, 0.01012658],
       [0.04761905, 0.95238095],
       [0.19371728, 0.80628272],
       [0.80526316, 0.19473684],
       [0.02777778, 0.97222222],
       [0.01052632, 0.98947368],
       [0.85492228, 0.14507772],
       [0.98205128, 0.01794872],
       [0.47286822, 0.52713178],
       [0.95024876, 0.04975124],
       [0.00512821, 0.99487179],
       [0.42447917, 0.57552083],
       [0.86633663, 0.13366337],
       [0.67792208, 0.32207792],
       [0.96758105, 0.03241895],
       [0.69010417, 0.30989583],
       [0.0835443 , 0.9164557 ],
       [0.06068602, 0.93931398],
       [0.00255102, 0.99744898],
       [0.04986877, 0.95013123],
       [0.9507772 , 0.0492228 ],
       [0.

In [65]:
# bagging classifier of sampling feature instead of sampling data

from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

bag_clf = BaggingClassifier(
    DecisionTreeClassifier(),n_estimators=500,max_samples=1.0,bootstrap=False,n_jobs=-1,bootstrap_features=True,max_features=0.5
)
bag_clf.fit(X_train,y_train)
y_pred = bag_clf.predict(X_test)
print(bag_clf.__class__.__name__,accuracy_score(y_test,y_pred))

BaggingClassifier 0.9


In [66]:
# Random forest
from sklearn.ensemble import RandomForestClassifier
rnd_clf = RandomForestClassifier(n_estimators=500,max_leaf_nodes=16,n_jobs=-1)
rnd_clf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=16,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=500,
                       n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [67]:
y_pred_rf = rnd_clf.predict(X_test)

In [68]:
accuracy_score(y_test,y_pred_rf)

1.0

In [73]:
#trying equivalent with bagging
bag_clf = BaggingClassifier(
 DecisionTreeClassifier(splitter="random", max_leaf_nodes=16),
    n_estimators=500,max_samples=1.0,bootstrap=True,n_jobs=-1
)
bag_clf.fit(X_train,y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None,
                                                        criterion='gini',
                                                        max_depth=None,
                                                        max_features=None,
                                                        max_leaf_nodes=16,
                                                        min_impurity_decrease=0.0,
                                                        min_impurity_split=None,
                                                        min_samples_leaf=1,
                                                        min_samples_split=2,
                                                        min_weight_fraction_leaf=0.0,
                                                        presort=False,
                                                        random_state=None,
                                                        splitter='random'),
    

In [74]:
y_pred_rf = bag_clf.predict(X_test)
accuracy_score(y_test,y_pred_rf)

1.0

In [75]:
#random forest feature importance
from sklearn.datasets import load_iris
iris = load_iris()
rnd_clf = RandomForestClassifier(n_estimators=500, n_jobs=-1)
rnd_clf.fit(iris["data"],iris["target"])
for name,score in zip(iris["feature_names"], rnd_clf.feature_importances_):
    print(name,score)

sepal length (cm) 0.09703221680722665
sepal width (cm) 0.024008170984204505
petal length (cm) 0.442466533613699
petal width (cm) 0.43649307859486985


In [76]:
from sklearn.ensemble import AdaBoostClassifier

In [91]:
# Adaboost - Adaptive boost
#SAMME.R - Stagewise Additive Modeling using a multiclass exponential loss function
ada_clf = AdaBoostClassifier(
  DecisionTreeClassifier(max_depth=1),n_estimators=5, algorithm="SAMME.R", learning_rate=0.5
)

ada_clf.fit(X_train,y_train)

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=DecisionTreeClassifier(class_weight=None,
                                                         criterion='gini',
                                                         max_depth=1,
                                                         max_features=None,
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         presort=False,
                                                         random_state=None,
                             

In [92]:
y_test_pred = ada_clf.predict(X_test)
accuracy_score(y_test,y_test_pred)

1.0

In [203]:
#Gradient boosting or Gradient Tree Boosting Regression  Trees

# was NOT WORKING before with accuracy_score because this is used for classifier only
from sklearn.ensemble import GradientBoostingRegressor
gbrt = GradientBoostingRegressor(max_depth=60,n_estimators=100,learning_rate=1.0)
X=  boston_data
y=  boston_target
X_train,X_test,y_train,y_test = X[:406],X[406:],y[:406],y[406:]

gbrt.fit(X_train,y_train)
y_test_pred = gbrt.predict([X_test[10]])
score = gbrt.score(X_test,y_test)
#print(X_test[10])
print(y_test[10])

7.5


In [204]:
print(score)

-0.4556626982216443


In [194]:
print(y_test_pred)

[10.4]


In [125]:
X = moons[0]
y = moons[1]
X_train,X_test,y_train,y_test = X[:80],X[80:],y[:80],y[80:]

X=  iris["data"]
y=  iris["target"]
X_train,X_test,y_train,y_test = X[:120],X[120:],y[:120],y[120:]

gbrt.fit(X_train,y_train)
y_test_pred = gbrt.predict(X_test)

#accuracy_score(y_test,y_test_pred)
y_test_pred.shape
accuracy_score(y_test,y_test_pred)


(30,)

In [126]:
y_test.shape

(30,)

In [127]:
y_test_pred

array([1.96107064, 1.84657359, 1.96107064, 1.84657359, 1.96107064,
       1.96107064, 1.44217687, 1.84657359, 1.96107064, 1.07671689,
       1.96107064, 1.96107064, 1.96107064, 1.07671689, 1.07671689,
       1.96107064, 1.96107064, 1.96107064, 1.44217687, 1.96107064,
       1.96107064, 1.96107064, 1.96107064, 1.96107064, 1.96107064,
       1.96107064, 1.84657359, 1.96107064, 1.96107064, 1.96107064])

In [119]:
accuracy_score(y_test,y_test_pred)

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [133]:
from sklearn.ensemble import GradientBoostingClassifier
gbrt = GradientBoostingClassifier(max_depth=2,n_estimators=3,learning_rate=1.0)
X=  iris["data"]
y=  iris["target"]
X_train,X_test,y_train,y_test = X[:120],X[120:],y[:120],y[120:]

gbrt.fit(X_train,y_train)
y_test_pred = gbrt.predict(X_test)

accuracy_score(y_test,y_test_pred)

print(y_test_pred)
print(y_test)


[2 2 2 1 2 2 1 1 2 1 2 2 2 1 1 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2]
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [155]:
from sklearn.datasets import load_boston

In [158]:
boston_home = load_boston()

In [167]:
feature_names = boston_home["feature_names"]
feature_names.shape

(13,)

In [168]:
boston_data = boston_home["data"]
boston_data.shape

(506, 13)

In [162]:
boston_target = boston_home["target"]

In [170]:
boston_target.shape

(506,)

In [214]:
X=  boston_data
y=  boston_target
X_train,X_test,y_train,y_test = X[:406],X[406:],y[:406],y[406:]


In [236]:

X=  boston_data
y=  boston_target
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
X_train,X_val,y_train,y_val = train_test_split(X,y,random_state=42)


In [237]:
X_train.shape,X_val.shape,y_train.shape,y_val.shape

((379, 13), (127, 13), (379,), (127,))

In [238]:
X_train.shape

(379, 13)

In [239]:
y_train.shape

(379,)

In [240]:
grbt = GradientBoostingRegressor(max_depth=2,n_estimators=120)
grbt.fit(X_train,y_train)
errors = [mean_squared_error(y_val,y_pred)
         for y_pred in gbrt.staged_predict(X_val)]
bst_n_estimator = np.argmin(errors)

print(bst_n_estimator)

0


In [242]:
grbt_best = GradientBoostingRegressor(max_depth=2,n_estimators=bst_n_estimator)
grbt_best.fit(X_train,y_train)

ValueError: n_estimators must be greater than 0 but was 0