In [1]:
from sklearn.datasets import load_boston
boston_home = load_boston()
feature_names = boston_home["feature_names"]
feature_names.shape
boston_data = boston_home["data"]
boston_data.shape
boston_target = boston_home["target"]
X=  boston_data
y=  boston_target
X_train,X_test,y_train,y_test = X[:406],X[406:],y[:406],y[406:]

In [8]:
X.shape
X[:1]

array([[6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
        6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
        4.980e+00]])

In [69]:
X_centered = X - X.mean(axis=0)
type(X_centered)

numpy.ndarray

In [70]:
X_centered[:1]

array([[-3.60720356e+00,  6.63636364e+00, -8.82677866e+00,
        -6.91699605e-02, -1.66950593e-02,  2.90365613e-01,
        -3.37490119e+00,  2.94957312e-01, -8.54940711e+00,
        -1.12237154e+02, -3.15553360e+00,  4.02259684e+01,
        -7.67306324e+00]])

In [71]:
#X_test = [[1,2],[4,4],[6,6]]
import numpy as np
X_test = np.array([[20, 8], [20,20],[80,4]])

In [72]:
X_test_centered = X_test- X_test.mean(axis=0)

In [73]:
print(X_test_centered)

[[-20.          -2.66666667]
 [-20.           9.33333333]
 [ 40.          -6.66666667]]


In [74]:
print(X_test)

[[20  8]
 [20 20]
 [80  4]]


In [75]:
print(X_test.mean(axis=0))

[40.         10.66666667]


In [76]:
U,s,V = np.linalg.svd(X_centered)

In [77]:
V[:2,:]

array([[ 2.92973218e-02, -4.35898000e-02,  2.83309382e-02,
        -5.55846350e-05,  4.49721818e-04, -1.16815860e-03,
         8.36335746e-02, -6.56163360e-03,  4.50053753e-02,
         9.49741169e-01,  5.60011721e-03, -2.91218514e-01,
         2.29433756e-02],
       [-6.66847277e-03, -1.17564821e-03,  4.94975624e-03,
         1.02678850e-04, -1.82069867e-06, -3.65750108e-04,
         5.72246652e-03, -3.53685109e-04,  8.61865948e-03,
         2.92406308e-01,  2.52898538e-03,  9.56180551e-01,
        -5.76719865e-03]])

In [78]:
V.T[:2,]

array([[ 2.92973218e-02, -6.66847277e-03, -1.14793645e-02,
         2.71309632e-02,  9.52338065e-01, -1.69050862e-01,
         2.16220534e-01,  1.24410586e-01,  1.37713177e-02,
        -1.66179883e-02, -1.99666297e-03, -1.99499182e-03,
         5.12974614e-04],
       [-4.35898000e-02, -1.17564821e-03,  6.32897481e-01,
         7.68058991e-01, -5.67213995e-03,  4.68215380e-02,
         3.51598379e-02, -5.13731838e-02,  2.35075239e-02,
         3.06891846e-02,  5.51190327e-03,  1.93735139e-04,
         1.27249747e-04]])

In [79]:
c1 = V.T[:,0]
c2 = V.T[:,1]

In [80]:
print(c1)

[ 2.92973218e-02 -4.35898000e-02  2.83309382e-02 -5.55846350e-05
  4.49721818e-04 -1.16815860e-03  8.36335746e-02 -6.56163360e-03
  4.50053753e-02  9.49741169e-01  5.60011721e-03 -2.91218514e-01
  2.29433756e-02]


In [81]:
W2 = V.T[:,:2]  # 2 as for 2 dimensions

In [82]:
X2D = X_centered.dot(W2)

In [83]:
X2D # 2 dimensions data reduced from 13 dimensiones data

array([[-119.81884272,    5.56005586],
       [-168.89015548,  -10.11620863],
       [-169.31170747,  -14.0805323 ],
       ...,
       [-138.38716306,   -0.9380922 ],
       [-137.50517338,   -4.2518251 ],
       [-139.19033295,   -1.00906423]])

In [84]:
#using scikit learn instead of numpy and python
from sklearn.decomposition import PCA

In [89]:
pca = PCA(n_components=2)
X2D = pca.fit_transform(X)

X2D

i wonder why it is different 2 col

In [97]:
pca.explained_variance_ratio_

array([8.58499809e-01, 7.83197054e-02, 4.41584549e-02, 1.44305686e-02,
       1.86954325e-03, 1.30580820e-03, 7.83009642e-04, 3.72875359e-04,
       1.81166604e-04, 6.37437617e-05, 1.17590801e-05, 3.42577258e-06,
       1.30681356e-07])

In [98]:
pca = PCA()
pca.fit(X_train)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [99]:
cumsum = np.cumsum(pca.explained_variance_ratio_) #Return the cumulative sum of the elements along a given axis.The default (None) is to compute the cumsum over the flattened array.

In [100]:
cumsum

array([0.85849981, 0.93681951, 0.98097797, 0.99540854, 0.99727808,
       0.99858389, 0.9993669 , 0.99973977, 0.99992094, 0.99998468,
       0.99999644, 0.99999987, 1.        ])

In [102]:
dimension = np.argmax(cumsum > 0.95) + 1

In [ ]:
# hence dimension =3 will cover 95% of variance

In [104]:
pca = PCA(n_components=0.95)
X_reduced = pca.fit_transform(X_train)

In [105]:
X_reduced # here X_reduced is data in dimensions which has 95 % variance

array([[ -59.58891458,  -12.47468146,   -6.77634568],
       [-110.47575584,   -2.29243568,  -33.87886032],
       [-112.22360179,   -2.11489135,  -20.0127386 ],
       ...,
       [ 313.35984928,  -32.93044604,   -7.79021745],
       [ 316.5479224 ,   29.88180227,   16.56916849],
       [ 315.86269421,  -20.94489708,   -8.12841474]])

In [108]:
#increamental PCA - do PCA in chunks to use less memory at a one
from sklearn.decomposition import IncrementalPCA
n_batches =50
int_pca = IncrementalPCA(n_components=4)
for X_batch in np.array_split(X_train, n_batches):
    int_pca.partial_fit(X_batch)
    
X_reduced = int_pca.transform(X_train)

In [110]:
X_reduced

array([[ -59.58879392,   12.47543296,    6.7801208 ,    5.57442921],
       [-110.47573024,    2.28843256,   33.88002627,    3.41328257],
       [-112.22356207,    2.11299547,   20.01271633,   -8.89758296],
       ...,
       [ 313.35963754,   32.92787431,    7.79381356,    0.79140917],
       [ 316.54739162,  -29.88516683,  -16.57699392,   -7.69012929],
       [ 315.86185426,   20.93830715,    8.12843382,    3.5199974 ]])

In [111]:
#Randomzed PCA
rnd_pca = PCA(n_components=4,svd_solver="randomized")

In [112]:
X_reduced = rnd_pca.fit_transform(X_train)

In [113]:
X_reduced

array([[ -59.58891458,  -12.47468146,   -6.77634568,   -5.59162722],
       [-110.47575584,   -2.29243568,  -33.87886032,   -3.42430727],
       [-112.22360179,   -2.11489135,  -20.0127386 ,    8.87870616],
       ...,
       [ 313.35984928,  -32.93044604,   -7.79021745,   -0.7907019 ],
       [ 316.5479224 ,   29.88180227,   16.56916849,    7.72069789],
       [ 315.86269421,  -20.94489708,   -8.12841474,   -3.51042345]])